spring:
  application:
    name: ad-eureka
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false #获取注册信息
    register-with-eureka: false #是否将自己注册到enureka
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

